# Generated by Django 4.0.4 on 2022-11-03 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_lesson_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('state', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.invoice')),
                ('name_of_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.course')),
            ],
        ),
    ]
