# Generated by Django 4.0.4 on 2023-04-30 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=15)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('name_of_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='course.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
