# Generated by Django 4.0.4 on 2023-01-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonStudentProfile',
        ),
    ]
