# Generated by Django 4.0.4 on 2022-11-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentprofile_student_id_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonstudentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='nonstudentprofile',
            name='program_of_interest',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=50, null=True),
        ),
    ]
