# Generated by Django 4.0.4 on 2022-11-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_nonstudentprofile_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='conv',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
