# Generated by Django 4.0.4 on 2022-11-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lesson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_group',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('NON-STUDENT', 'Non-Student')], max_length=20, null=True),
        ),
    ]
