# Generated by Django 4.0.4 on 2023-05-02 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_comment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Lesson',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='course.lesson'),
        ),
    ]
