# Generated by Django 4.0.4 on 2023-04-08 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.CharField(max_length=40)),
                ('task_completed', models.TextField(blank=True, max_length=5000, null=True)),
                ('task_in_progress', models.TextField(blank=True, max_length=5000, null=True)),
                ('next_day_task', models.TextField(blank=True, max_length=5000, null=True)),
                ('problem_or_challenges', models.TextField(blank=True, max_length=5000, null=True)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('week_number',),
            },
        ),
    ]
