# Generated by Django 4.0.4 on 2023-04-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
