# Generated by Django 4.0.4 on 2022-10-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_field', models.CharField(max_length=255)),
                ('about_intern', models.CharField(max_length=255)),
                ('about_supervision', models.CharField(max_length=255)),
                ('about_skills', models.CharField(max_length=255)),
                ('about_solutions', models.CharField(max_length=255)),
                ('about_us', models.CharField(max_length=255)),
                ('about_views', models.CharField(max_length=255)),
                ('follow_us', models.CharField(max_length=255)),
                ('contact_us', models.CharField(max_length=255)),
                ('pricing', models.CharField(max_length=255)),
                ('demo', models.CharField(max_length=255)),
                ('partners', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-demo',),
            },
        ),
    ]
