# Generated by Django 4.0.4 on 2022-11-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Landing_Page_Information',
        ),
    ]
