# Generated by Django 4.0.4 on 2022-11-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_home_landing_page_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing_page_information',
            name='first_video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landing_page_information',
            name='fourth_video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landing_page_information',
            name='second_video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='landing_page_information',
            name='third_video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
