# Generated by Django 4.0.4 on 2022-11-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_introduction_videos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Introduction_Videos',
            new_name='Introduction_Video',
        ),
    ]
