# Generated by Django 4.0.4 on 2022-12-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_introduction_videos_introduction_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
