# Generated by Django 4.0.4 on 2023-01-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landing_page_information',
            options={'ordering': ('-information_name',)},
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='about_intern',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='about_skills',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='about_solutions',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='about_supervision',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='about_views',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='contact_us',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='demo',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='follow_us',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='landing_page_information',
            name='why_field',
        ),
        migrations.AddField(
            model_name='landing_page_information',
            name='information_description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='landing_page_information',
            name='information_name',
            field=models.CharField(default='why_field', max_length=30),
            preserve_default=False,
        ),
    ]
